# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    network_mode: "host"
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8091:8091"
    depends_on:
      - backend
    restart: unless-stopped



