
[gwrite.json_t]
document_start = "{{"
document_end = "}}\n"
line_join = ","
layer_join = ","
layer_start = "\n\t\"Layer\": {{"
layer_end = "\t}}\n"
line_start = "\n\t\t\"line{index:}\": [\n"
line_end = "\n\t\t]"
segment = "\t\t{{\n\t\t\t\"X\": {x:.2f},\n\t\t\t\"Y\": {y:.2f}\n\t\t}},\n"
segment_last = "\t\t{{\n\t\t\t\"X\": {x:.2f},\n\t\t\t\"Y\": {y:.2f}\n\t\t}}"
unit = "mm"
invert_y = true
