name: Deploy Plotter Pi Software

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Activate Python
      run: 
        source /home/pi/sofia-plotter/bin/python
        
    - name: Install reqs
      run: python -m pip install -r python/requirements.txt
